using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;

namespace AIBT.CodeGen
{
    internal static class GeneratedMetadataEmitter
    {
        private const string NodeAttribute = "AIBT.Burst.AibtBurstNodeAttribute";
        private const string DocumentationAttribute = "AIBT.Burst.AibtNodeDocumentationAttribute";
        private const string ConfigFieldAttribute = "AIBT.Burst.AibtConfigFieldAttribute";
        private const string MemoryFieldAttribute = "AIBT.Burst.AibtMemoryFieldAttribute";
        private const string BlackboardBindingAttribute = "AIBT.Burst.AibtBlackboardBindingAttribute";
        private const string ValueAttribute = "AIBT.Burst.AibtBurstValueAttribute";
        private const string ValueFieldAttribute = "AIBT.Burst.AibtValueFieldAttribute";

        internal static string EmitShard(INamedTypeSymbol shard, IReadOnlyList<INamedTypeSymbol> nodeTypes)
        {
            var nodes = nodeTypes.Select(ReadNode).OrderBy(value => value.TypeId, Utf8Comparer.Instance).ThenBy(value => value.Version).ToArray();
            var registry = Registry(nodes);
            var descriptor = Descriptor(nodes);
            var shardAttribute = Attribute(shard, "AIBT.Burst.AibtCatalogShardAttribute")!;
            var shardId = (string)shardAttribute.ConstructorArguments[0].Value!;
            var shardVersion = (uint)shardAttribute.ConstructorArguments[1].Value!;
            var builder = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
            if (!shard.ContainingNamespace.IsGlobalNamespace)
                builder.Append("namespace ").Append(shard.ContainingNamespace.ToDisplayString()).AppendLine("\n{");
            builder.Append("public partial struct ").Append(shard.Name).AppendLine();
            builder.AppendLine("{");
            builder.AppendLine("    public const bool IsUsable = true;");
            builder.AppendLine("    public const uint AbiVersion = 2u;");
            builder.AppendLine("    public static class AibtGeneratedMetadata");
            builder.AppendLine("    {");
            builder.Append("        public const string ShardId = ").Append(Literal(shardId)).AppendLine(";");
            builder.Append("        public const uint ShardVersion = ").Append(shardVersion.ToString(CultureInfo.InvariantCulture)).AppendLine("u;");
            builder.Append("        public const string ManifestRegistryJson = ").Append(Literal(registry)).AppendLine(";");
            builder.Append("        public const string NodeRegistryHash = ").Append(Literal(Sha256(registry))).AppendLine(";");
            builder.Append("        public const string CanonicalDescriptorJson = ").Append(Literal(descriptor)).AppendLine(";");
            builder.Append("        public const string DescriptorHash = ").Append(Literal(Sha256(descriptor))).AppendLine(";");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            if (!shard.ContainingNamespace.IsGlobalNamespace) builder.AppendLine("}");
            return builder.ToString();
        }

        private static NodeInfo ReadNode(INamedTypeSymbol type)
        {
            var node = Attribute(type, NodeAttribute)!;
            var docs = Attribute(type, DocumentationAttribute)!;
            var args = node.ConstructorArguments;
            var configuration = Layout((INamedTypeSymbol)args[3].Value!, ConfigFieldAttribute, true);
            var memory = Layout((INamedTypeSymbol)args[4].Value!, MemoryFieldAttribute, false);
            var bindings = ReadBindings(configuration.Fields);
            return new NodeInfo(
                type,
                (string)args[0].Value!,
                (uint)args[1].Value!,
                Convert.ToByte(args[2].Value, CultureInfo.InvariantCulture),
                Convert.ToByte(args[5].Value, CultureInfo.InvariantCulture),
                (bool)args[6].Value!,
                Convert.ToByte(args[7].Value, CultureInfo.InvariantCulture),
                Convert.ToByte(args[8].Value, CultureInfo.InvariantCulture),
                Convert.ToByte(args[9].Value, CultureInfo.InvariantCulture),
                (string)docs.ConstructorArguments[0].Value!,
                (string)docs.ConstructorArguments[1].Value!,
                (string)docs.ConstructorArguments[2].Value!,
                (string)docs.ConstructorArguments[3].Value!,
                docs.ConstructorArguments[4].Values.Select(value => (string)value.Value!).OrderBy(value => value, Utf8Comparer.Instance).ToArray(),
                configuration,
                memory,
                bindings,
                Attribute(type, "AIBT.Burst.AibtObserverConditionAttribute") != null,
                Attribute(type, "AIBT.Burst.AibtRandomStreamAttribute") != null);
        }

        private static LayoutInfo Layout(INamedTypeSymbol type, string fieldAttribute, bool configuration)
        {
            var fields = type.GetMembers().OfType<IFieldSymbol>().Where(field => !field.IsStatic && !field.IsImplicitlyDeclared)
                .Select(field => ReadField(field, fieldAttribute, configuration)).OrderBy(field => field.Id, Utf8Comparer.Instance).ToArray();
            uint cursor = 0;
            byte alignment = 1;
            foreach (var field in fields)
            {
                cursor = Align(cursor, field.Alignment);
                field.Offset = cursor;
                cursor = checked(cursor + field.Size);
                if (field.Alignment > alignment) alignment = field.Alignment;
            }
            return new LayoutInfo(fields, Align(cursor, alignment), alignment);
        }

        private static FieldInfo ReadField(IFieldSymbol field, string fieldAttribute, bool configuration)
        {
            var attribute = Attribute(field, fieldAttribute)!;
            var id = (string)attribute.ConstructorArguments[0].Value!;
            var typeId = (string)attribute.ConstructorArguments[1].Value!;
            var version = (uint)attribute.ConstructorArguments[2].Value!;
            if (configuration && IsHandle(field.Type)) return new FieldInfo(field, id, typeId, version, 4, 4, 12);
            var shape = Shape(field.Type);
            return new FieldInfo(field, id, typeId, version, shape.Size, shape.Alignment, shape.Encoding);
        }

        private static BindingInfo[] ReadBindings(IEnumerable<FieldInfo> fields)
        {
            var values = new List<BindingInfo>();
            foreach (var field in fields)
            {
                var attribute = field.Symbol.GetAttributes().FirstOrDefault(candidate => IsBinding(candidate.AttributeClass?.ToDisplayString()));
                if (attribute == null) continue;
                var name = attribute.AttributeClass!.ToDisplayString();
                var args = attribute.ConstructorArguments;
                var id = (string)args[0].Value!;
                field.BindingId = id;
                byte kind, scope = byte.MaxValue, phase = 0;
                var types = new List<TypeInfo>();
                if (name == BlackboardBindingAttribute)
                {
                    var access = Convert.ToByte(args[1].Value, CultureInfo.InvariantCulture);
                    kind = access;
                    scope = Convert.ToByte(args[2].Value, CultureInfo.InvariantCulture);
                    types.Add(new TypeInfo(0, (string)args[3].Value!, (uint)args[4].Value!, ((INamedTypeSymbol)field.Symbol.Type).TypeArguments[0]));
                }
                else if (name.EndsWith("AibtSnapshotBindingAttribute", StringComparison.Ordinal))
                { kind = 3; types.Add(new TypeInfo(0, (string)args[1].Value!, (uint)args[2].Value!, ((INamedTypeSymbol)field.Symbol.Type).TypeArguments[0])); }
                else if (name.EndsWith("AibtCommandBindingAttribute", StringComparison.Ordinal))
                { kind = 4; phase = 1; types.Add(new TypeInfo(1, (string)args[1].Value!, (uint)args[2].Value!, ((INamedTypeSymbol)field.Symbol.Type).TypeArguments[0])); }
                else if (name.EndsWith("AibtAsyncOperationBindingAttribute", StringComparison.Ordinal))
                { var arguments = ((INamedTypeSymbol)field.Symbol.Type).TypeArguments; kind = 5; phase = 3; types.Add(new TypeInfo(2, (string)args[1].Value!, (uint)args[2].Value!, arguments[0])); types.Add(new TypeInfo(3, (string)args[3].Value!, (uint)args[4].Value!, arguments[1])); }
                else
                { kind = 6; phase = 4; types.Add(new TypeInfo(4, (string)args[1].Value!, (uint)args[2].Value!, ((INamedTypeSymbol)field.Symbol.Type).TypeArguments[0])); }
                values.Add(new BindingInfo(id, kind, scope, phase, types.ToArray()));
            }
            var ordered = values.OrderBy(value => value.Id, Utf8Comparer.Instance).ToArray();
            for (var index = 0; index < ordered.Length; index++) ordered[index].Ordinal = (uint)index;
            return ordered;
        }

        private static string Registry(IReadOnlyList<NodeInfo> nodes)
        {
            var builder = new JsonBuilder();
            builder.BeginObject(); builder.Property("format", "aibt-node-registry"); builder.Property("formatVersion", 1u);
            builder.PropertyName("manifests"); builder.BeginArray();
            for (var index = 0; index < nodes.Count; index++) Manifest(builder, nodes[index]);
            builder.EndArray(); builder.EndObject();
            return builder.Finish();
        }

        private static void Manifest(JsonBuilder json, NodeInfo node)
        {
            json.BeginObject();
            json.Property("typeId", node.TypeId); json.Property("version", node.Version);
            json.Property("summary", node.Summary); json.Property("category", node.Category);
            json.Property("kind", node.Kind == 0 ? "condition" : "action");
            json.Property("whenToUse", node.WhenToUse); json.Property("whenNotToUse", node.WhenNotToUse);
            json.PropertyName("parameters"); json.BeginObject();
            foreach (var field in node.Configuration.Fields.Where(field => field.Encoding != 12))
            {
                json.PropertyName(field.Id); json.BeginObject();
                json.Property("type", field.Encoding == 0 ? "boolean" : field.Encoding == 6 ? "uint32" : "uint64");
                json.Property("required", true);
                json.PropertyName("packing"); json.BeginObject(); json.Property("offset", field.Offset); json.Property("size", field.Size); json.Property("alignment", field.Alignment); json.EndObject();
                json.EndObject();
            }
            json.EndObject();
            json.PropertyName("childPolicy"); json.BeginObject(); json.Property("minimum", 0u); json.Property("maximum", 0u); json.Property("ordered", true); json.EndObject();
            EmptyArray(json, "reads"); EmptyArray(json, "writes"); EmptyArray(json, "sideEffects");
            json.PropertyName("possibleStatuses"); json.BeginArray();
            if ((node.StatusMask & 2) != 0) json.Value("failure"); if ((node.StatusMask & 4) != 0) json.Value("running"); if ((node.StatusMask & 1) != 0) json.Value("success");
            json.EndArray();
            json.PropertyName("memory"); json.BeginObject(); json.Property("size", node.Memory.Size); json.Property("alignment", node.Memory.Alignment); json.Property("lifetime", node.MemoryLifetime == 0 ? "activation" : "instance"); json.EndObject();
            json.PropertyName("configuration"); json.BeginObject(); json.Property("size", node.Configuration.Size); json.Property("alignment", node.Configuration.Alignment); json.EndObject();
            json.Property("cancellation", node.Cancellation == 0 ? "not-applicable" : node.Cancellation == 1 ? "abort-only" : "command");
            json.Property("executionDomain", "burst"); json.Property("deterministic", node.Deterministic);
            json.Property("costHint", new[] { "trivial", "low", "medium", "high", "variable" }[node.Cost]);
            json.PropertyName("examples"); json.BeginArray();
            foreach (var example in node.Examples)
            {
                json.BeginObject(); json.Property("title", example); json.PropertyName("parameters"); json.BeginObject();
                foreach (var field in node.Configuration.Fields.Where(field => field.Encoding != 12))
                { json.PropertyName(field.Id); if (field.Encoding == 0) json.Value(false); else json.Value(0u); }
                json.EndObject(); json.Property("expectedBehavior", node.Summary); json.EndObject();
            }
            json.EndArray(); json.EndObject();
        }

        private static string Descriptor(IReadOnlyList<NodeInfo> nodes)
        {
            var json = new JsonBuilder(compact: true); json.BeginObject(); json.Property("abiVersion", 2u);
            json.PropertyName("registeredTypes"); json.BeginArray();
            foreach (var type in RegisteredTypes(nodes)) RegisteredType(json, type);
            json.EndArray();
            json.PropertyName("nodes"); json.BeginArray();
            foreach (var node in nodes)
            {
                json.BeginObject(); json.Property("typeId", node.TypeId); json.Property("version", node.Version);
                json.Property("callbackCapabilities", (uint)(node.Observer ? 0x1f : 0x0f)); json.Property("hasRandom", node.Random);
                json.Property("configurationHash", LayoutHash(node, true)); json.Property("memoryHash", LayoutHash(node, false)); json.Property("accessHash", AccessHash(node));
                json.PropertyName("configuration"); Fields(json, node.Configuration); json.PropertyName("memory"); Fields(json, node.Memory);
                json.PropertyName("bindings"); json.BeginArray();
                foreach (var binding in node.Bindings)
                {
                    json.BeginObject(); json.Property("id", binding.Id); json.Property("numericId", binding.NumericId.ToString("x16", CultureInfo.InvariantCulture));
                    json.Property("kind", binding.Kind); json.Property("scope", binding.Scope); json.Property("phase", binding.Phase); json.Property("ordinal", binding.Ordinal);
                    json.PropertyName("types"); json.BeginArray(); foreach (var type in binding.Types) { var shape = Shape(type.Symbol); var valueAttribute = Attribute((INamedTypeSymbol)type.Symbol, ValueAttribute); var registered = valueAttribute != null; json.BeginObject(); json.Property("role", type.Role); json.Property("id", type.Id); json.Property("version", type.Version); json.Property("size", shape.Size); json.Property("alignment", shape.Alignment); json.Property("encoding", shape.Encoding); json.Property("schemaId", registered ? (string)valueAttribute!.ConstructorArguments[2].Value! : ""); json.Property("schemaHash", registered ? SchemaHash(type.Symbol) : new string('0', 64)); json.Property("equalityContractId", registered ? "69e3a80e385e338e" : "0000000000000000"); json.EndObject(); } json.EndArray(); json.EndObject();
                }
                json.EndArray(); json.EndObject();
            }
            json.EndArray(); json.EndObject(); return json.Finish();
        }

        private static INamedTypeSymbol[] RegisteredTypes(IEnumerable<NodeInfo> nodes)
        {
            var values = new Dictionary<string, INamedTypeSymbol>(StringComparer.Ordinal);
            Action<ITypeSymbol> add = null!;
            add = symbol =>
            {
                if (!(symbol is INamedTypeSymbol named) || Attribute(named, ValueAttribute) == null) return;
                var attribute = Attribute(named, ValueAttribute)!;
                var identity = (string)attribute.ConstructorArguments[0].Value! + "\0" + ((uint)attribute.ConstructorArguments[1].Value!).ToString(CultureInfo.InvariantCulture);
                if (values.ContainsKey(identity)) return;
                values.Add(identity, named);
                foreach (var field in named.GetMembers().OfType<IFieldSymbol>().Where(field => !field.IsStatic && !field.IsImplicitlyDeclared)) add(field.Type);
            };
            foreach (var node in nodes)
            {
                foreach (var field in node.Configuration.Fields) add(field.Symbol.Type);
                foreach (var field in node.Memory.Fields) add(field.Symbol.Type);
                foreach (var binding in node.Bindings) foreach (var type in binding.Types) add(type.Symbol);
            }
            return values.Values.OrderBy(value => (string)Attribute(value, ValueAttribute)!.ConstructorArguments[0].Value!, Utf8Comparer.Instance)
                .ThenBy(value => (uint)Attribute(value, ValueAttribute)!.ConstructorArguments[1].Value!).ToArray();
        }

        private static void RegisteredType(JsonBuilder json, INamedTypeSymbol type)
        {
            var attribute = Attribute(type, ValueAttribute)!;
            var typeId = (string)attribute.ConstructorArguments[0].Value!;
            var version = (uint)attribute.ConstructorArguments[1].Value!;
            var schemaId = (string)attribute.ConstructorArguments[2].Value!;
            var layout = Layout(type, ValueFieldAttribute, false);
            json.BeginObject();
            json.Property("id", typeId); json.Property("numericId", Numeric(typeId).ToString("x16", CultureInfo.InvariantCulture));
            json.Property("version", version); json.Property("schemaId", schemaId); json.Property("numericSchemaId", Numeric(schemaId).ToString("x16", CultureInfo.InvariantCulture));
            json.Property("schemaHash", SchemaHash(type)); json.Property("equalityContractId", "69e3a80e385e338e");
            json.Property("size", layout.Size); json.Property("alignment", layout.Alignment);
            json.PropertyName("fields"); json.BeginArray();
            foreach (var field in layout.Fields)
            {
                json.BeginObject(); json.Property("id", field.Id); json.Property("numericId", Numeric(field.Id).ToString("x16", CultureInfo.InvariantCulture));
                json.Property("type", field.TypeId); json.Property("version", field.Version); json.Property("schemaHash", SchemaHash(field.Symbol.Type));
                json.Property("offset", field.Offset); json.Property("size", field.Size); json.Property("alignment", field.Alignment); json.Property("encoding", field.Encoding); json.EndObject();
            }
            json.EndArray(); json.EndObject();
        }

        private static void Fields(JsonBuilder json, LayoutInfo layout)
        {
            json.BeginObject(); json.Property("size", layout.Size); json.Property("alignment", layout.Alignment); json.PropertyName("fields"); json.BeginArray();
            foreach (var field in layout.Fields) { var registered = field.Encoding == 13; var valueAttribute = registered ? Attribute((INamedTypeSymbol)field.Symbol.Type, ValueAttribute) : null; json.BeginObject(); json.Property("id", field.Id); json.Property("type", field.TypeId); json.Property("version", field.Version); json.Property("offset", field.Offset); json.Property("size", field.Size); json.Property("alignment", field.Alignment); json.Property("encoding", field.Encoding); json.Property("bindingId", field.BindingId ?? ""); json.Property("schemaId", registered ? (string)valueAttribute!.ConstructorArguments[2].Value! : ""); json.Property("schemaHash", registered ? SchemaHash(field.Symbol.Type) : new string('0', 64)); json.Property("equalityContractId", registered ? "69e3a80e385e338e" : "0000000000000000"); json.EndObject(); }
            json.EndArray(); json.EndObject();
        }

        private static string LayoutHash(NodeInfo node, bool configuration)
        {
            var layout = configuration ? node.Configuration : node.Memory;
            var writer = new ByteWriter(configuration ? "AIBT-CONFIG-LAYOUT-V1\0" : "AIBT-MEMORY-LAYOUT-V1\0");
            writer.U32(1); writer.String(node.TypeId); writer.U32(node.Version); writer.U32(layout.Size); writer.U8(layout.Alignment); writer.U32((uint)layout.Fields.Length);
            foreach (var field in layout.Fields) { writer.String(field.Id); writer.U64(Numeric(field.Id)); writer.String(field.TypeId); writer.U32(field.Version); writer.HashHex(SchemaHash(field.Symbol.Type)); writer.U32(field.Offset); writer.U32(field.Size); writer.U8(field.Alignment); writer.U8(field.Encoding); }
            var padding = Padding(layout); writer.U32((uint)padding.Count); foreach (var range in padding) { writer.U32(range.Item1); writer.U32(range.Item2); }
            return writer.Hash();
        }

        private static string AccessHash(NodeInfo node)
        {
            var writer = new ByteWriter("AIBT-ACCESS-LAYOUT-V1\0"); writer.U32(1); writer.String(node.TypeId); writer.U32(node.Version); writer.U32((uint)node.Bindings.Length);
            foreach (var binding in node.Bindings)
            {
                writer.String(binding.Id); writer.U64(binding.NumericId); writer.U8(binding.Kind); writer.U8(binding.Scope); writer.U8(binding.Phase); writer.U32(binding.Ordinal); writer.U32((uint)binding.Types.Length);
                foreach (var type in binding.Types) { writer.U8(type.Role); writer.String(type.Id); writer.U64(Numeric(type.Id)); writer.U32(type.Version); writer.HashHex(SchemaHash(type.Symbol)); }
            }
            return writer.Hash();
        }

        private static string SchemaHash(ITypeSymbol type)
        {
            if (!(type is INamedTypeSymbol named) || Attribute(named, ValueAttribute) == null)
                return new string('0', 64);
            var attribute = Attribute(named, ValueAttribute)!;
            var typeId = (string)attribute.ConstructorArguments[0].Value!;
            var version = (uint)attribute.ConstructorArguments[1].Value!;
            var schemaId = (string)attribute.ConstructorArguments[2].Value!;
            var layout = Layout(named, ValueFieldAttribute, false);
            var writer = new ByteWriter("AIBT-VALUE-SCHEMA-V1\0");
            writer.U32(1); writer.String(typeId); writer.U64(Numeric(typeId)); writer.U32(version);
            writer.String(schemaId); writer.U64(Numeric(schemaId)); writer.U32(layout.Size); writer.U8(layout.Alignment); writer.U32((uint)layout.Fields.Length);
            foreach (var field in layout.Fields)
            {
                writer.String(field.Id); writer.U64(Numeric(field.Id)); writer.String(field.TypeId); writer.U64(Numeric(field.TypeId)); writer.U32(field.Version);
                writer.HashHex(SchemaHash(field.Symbol.Type)); writer.U32(field.Offset); writer.U32(field.Size); writer.U8(field.Alignment); writer.U8(field.Encoding);
            }
            return writer.Hash();
        }

        private static List<Tuple<uint, uint>> Padding(LayoutInfo layout)
        {
            var ordered = layout.Fields.OrderBy(field => field.Offset).ToArray(); var result = new List<Tuple<uint, uint>>(); uint cursor = 0;
            foreach (var field in ordered) { if (field.Offset > cursor) result.Add(Tuple.Create(cursor, field.Offset - cursor)); cursor = field.Offset + field.Size; }
            if (layout.Size > cursor) result.Add(Tuple.Create(cursor, layout.Size - cursor)); return result;
        }

        private static TypeShape Shape(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean: return new TypeShape(1, 1, 0);
                case SpecialType.System_SByte: return new TypeShape(1, 1, 1);
                case SpecialType.System_Byte: return new TypeShape(1, 1, 2);
                case SpecialType.System_Int16: return new TypeShape(2, 2, 3);
                case SpecialType.System_UInt16: return new TypeShape(2, 2, 4);
                case SpecialType.System_Int32: return new TypeShape(4, 4, 5);
                case SpecialType.System_UInt32: return new TypeShape(4, 4, 6);
                case SpecialType.System_Int64: return new TypeShape(8, 8, 7);
                case SpecialType.System_UInt64: return new TypeShape(8, 8, 8);
                case SpecialType.System_Single: return new TypeShape(4, 4, 9);
                case SpecialType.System_Double: return new TypeShape(8, 8, 10);
            }
            var name = type.ToDisplayString();
            if (name == "AIBT.Float2Value") return new TypeShape(8, 4, 11);
            if (name == "AIBT.Float3Value") return new TypeShape(12, 4, 11);
            if (name == "AIBT.QuaternionValue") return new TypeShape(16, 4, 11);
            if (name == "AIBT.AgentId" || name == "AIBT.EntityId") return new TypeShape(8, 8, 11);
            if (name == "AIBT.OperationId") return new TypeShape(24, 8, 11);
            if (name == "AIBT.AssetId") return new TypeShape(32, 8, 11);
            if (name == "Unity.Collections.FixedString32Bytes") return new TypeShape(32, 2, 11);
            if (name == "Unity.Collections.FixedString64Bytes") return new TypeShape(64, 2, 11);
            if (name == "Unity.Collections.FixedString128Bytes") return new TypeShape(128, 2, 11);
            if (name == "Unity.Collections.FixedString512Bytes") return new TypeShape(512, 2, 11);
            var named = (INamedTypeSymbol)type;
            var layout = Layout(named, ValueFieldAttribute, false);
            return new TypeShape(layout.Size, layout.Alignment, 13);
        }

        private static bool IsHandle(ITypeSymbol type) => type is INamedTypeSymbol named && named.IsGenericType && new[] { "BlackboardReadHandle<T>", "BlackboardWriteHandle<T>", "BlackboardReadWriteHandle<T>", "SnapshotReadHandle<T>", "CommandHandle<T>", "AsyncOperationHandle<TStart, TCancel>", "CompletionHandle<T>" }.Contains(named.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat));
        private static bool IsBinding(string? name) => name != null && (name == BlackboardBindingAttribute || name.EndsWith("AibtSnapshotBindingAttribute", StringComparison.Ordinal) || name.EndsWith("AibtCommandBindingAttribute", StringComparison.Ordinal) || name.EndsWith("AibtAsyncOperationBindingAttribute", StringComparison.Ordinal) || name.EndsWith("AibtCompletionBindingAttribute", StringComparison.Ordinal));
        private static AttributeData? Attribute(ISymbol symbol, string name) => symbol.GetAttributes().FirstOrDefault(value => value.AttributeClass?.ToDisplayString() == name);
        private static uint Align(uint value, byte alignment) => checked((value + (uint)alignment - 1) & ~((uint)alignment - 1));
        private static ulong Numeric(string value) { var hash = 14695981039346656037UL; foreach (var octet in new UTF8Encoding(false, true).GetBytes(value)) { hash ^= octet; hash *= 1099511628211UL; } return hash; }
        private static string Sha256(string value) { using (var hash = SHA256.Create()) return Hex(hash.ComputeHash(Encoding.UTF8.GetBytes(value))); }
        private static string Hex(byte[] bytes) { var builder = new StringBuilder(bytes.Length * 2); foreach (var value in bytes) builder.Append(value.ToString("x2", CultureInfo.InvariantCulture)); return builder.ToString(); }
        private static string Literal(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n") + "\"";
        private static void EmptyArray(JsonBuilder json, string name) { json.PropertyName(name); json.BeginArray(); json.EndArray(); }

        private sealed class NodeInfo
        {
            internal NodeInfo(INamedTypeSymbol symbol, string typeId, uint version, byte kind, byte memoryLifetime, bool deterministic, byte cancellation, byte cost, byte statusMask, string summary, string category, string whenToUse, string whenNotToUse, string[] examples, LayoutInfo configuration, LayoutInfo memory, BindingInfo[] bindings, bool observer, bool random)
            { Symbol = symbol; TypeId = typeId; Version = version; Kind = kind; MemoryLifetime = memoryLifetime; Deterministic = deterministic; Cancellation = cancellation; Cost = cost; StatusMask = statusMask; Summary = summary; Category = category; WhenToUse = whenToUse; WhenNotToUse = whenNotToUse; Examples = examples; Configuration = configuration; Memory = memory; Bindings = bindings; Observer = observer; Random = random; }
            internal INamedTypeSymbol Symbol; internal string TypeId; internal uint Version; internal byte Kind, MemoryLifetime, Cancellation, Cost, StatusMask; internal bool Deterministic, Observer, Random; internal string Summary, Category, WhenToUse, WhenNotToUse; internal string[] Examples; internal LayoutInfo Configuration, Memory; internal BindingInfo[] Bindings;
        }
        private sealed class LayoutInfo { internal LayoutInfo(FieldInfo[] fields, uint size, byte alignment) { Fields = fields; Size = size; Alignment = alignment; } internal FieldInfo[] Fields; internal uint Size; internal byte Alignment; }
        private sealed class FieldInfo { internal FieldInfo(IFieldSymbol symbol, string id, string typeId, uint version, uint size, byte alignment, byte encoding) { Symbol = symbol; Id = id; TypeId = typeId; Version = version; Size = size; Alignment = alignment; Encoding = encoding; } internal IFieldSymbol Symbol; internal string Id, TypeId; internal string? BindingId; internal uint Version, Size, Offset; internal byte Alignment, Encoding; }
        private sealed class BindingInfo { internal BindingInfo(string id, byte kind, byte scope, byte phase, TypeInfo[] types) { Id = id; NumericId = Numeric(id); Kind = kind; Scope = scope; Phase = phase; Types = types; } internal string Id; internal ulong NumericId; internal byte Kind, Scope, Phase; internal uint Ordinal; internal TypeInfo[] Types; }
        private sealed class TypeInfo { internal TypeInfo(byte role, string id, uint version, ITypeSymbol symbol) { Role = role; Id = id; Version = version; Symbol = symbol; } internal byte Role; internal string Id; internal uint Version; internal ITypeSymbol Symbol; }
        private readonly struct TypeShape { internal TypeShape(uint size, byte alignment, byte encoding) { Size = size; Alignment = alignment; Encoding = encoding; } internal uint Size { get; } internal byte Alignment { get; } internal byte Encoding { get; } }

        private sealed class Utf8Comparer : IComparer<string> { internal static readonly Utf8Comparer Instance = new Utf8Comparer(); public int Compare(string x, string y) { var left = Encoding.UTF8.GetBytes(x); var right = Encoding.UTF8.GetBytes(y); for (var i = 0; i < Math.Min(left.Length, right.Length); i++) if (left[i] != right[i]) return left[i].CompareTo(right[i]); return left.Length.CompareTo(right.Length); } }

        private sealed class ByteWriter
        {
            private readonly MemoryStream _stream = new MemoryStream();
            internal ByteWriter(string domain) { var bytes = Encoding.UTF8.GetBytes(domain); _stream.Write(bytes, 0, bytes.Length); }
            internal void U8(byte value) => _stream.WriteByte(value); internal void U32(uint value) { U8((byte)value); U8((byte)(value >> 8)); U8((byte)(value >> 16)); U8((byte)(value >> 24)); } internal void U64(ulong value) { U32((uint)value); U32((uint)(value >> 32)); }
            internal void String(string value) { var bytes = Encoding.UTF8.GetBytes(value); U32((uint)bytes.Length); _stream.Write(bytes, 0, bytes.Length); }
            internal void ZeroHash() { for (var i = 0; i < 32; i++) U8(0); }
            internal void HashHex(string value) { for (var i = 0; i < value.Length; i += 2) U8(byte.Parse(value.Substring(i, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture)); }
            internal string Hash() { using (var sha = SHA256.Create()) return Hex(sha.ComputeHash(_stream.ToArray())); }
        }

        private sealed class JsonBuilder
        {
            private readonly StringBuilder _builder = new StringBuilder(); private readonly Stack<bool> _first = new Stack<bool>(); private readonly bool _compact; private int _indent; private bool _afterName;
            internal JsonBuilder(bool compact = false) { _compact = compact; }
            internal void BeginObject() { Prefix(); _builder.Append('{'); _first.Push(true); _indent++; _afterName = false; }
            internal void EndObject() { var empty = _first.Pop(); _indent--; if (!empty) NewLine(); _builder.Append('}'); _afterName = false; }
            internal void BeginArray() { Prefix(); _builder.Append('['); _first.Push(true); _indent++; _afterName = false; }
            internal void EndArray() { var empty = _first.Pop(); _indent--; if (!empty) NewLine(); _builder.Append(']'); _afterName = false; }
            internal void PropertyName(string name) { Element(); WriteString(name); _builder.Append(_compact ? ":" : ": "); _afterName = true; }
            internal void Property(string name, string value) { PropertyName(name); Value(value); } internal void Property(string name, uint value) { PropertyName(name); Value(value); } internal void Property(string name, byte value) { PropertyName(name); Value((uint)value); } internal void Property(string name, bool value) { PropertyName(name); Value(value); }
            internal void Value(string value) { Prefix(); WriteString(value); } internal void Value(uint value) { Prefix(); _builder.Append(value.ToString(CultureInfo.InvariantCulture)); } internal void Value(bool value) { Prefix(); _builder.Append(value ? "true" : "false"); }
            internal string Finish() => _builder.Append(_compact ? string.Empty : "\n").ToString();
            private void Prefix() { if (_afterName) { _afterName = false; return; } Element(); }
            private void Element() { if (_first.Count == 0) return; var first = _first.Pop(); if (!first) _builder.Append(','); _first.Push(false); NewLine(); }
            private void NewLine() { if (_compact) return; _builder.Append('\n').Append(' ', _indent * 2); }
            private void WriteString(string value) { _builder.Append('"'); foreach (var c in value) { switch (c) { case '"': _builder.Append("\\\""); break; case '\\': _builder.Append("\\\\"); break; case '\b': _builder.Append("\\b"); break; case '\f': _builder.Append("\\f"); break; case '\n': _builder.Append("\\n"); break; case '\r': _builder.Append("\\r"); break; case '\t': _builder.Append("\\t"); break; default: if (c < 0x20) _builder.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture)); else _builder.Append(c); break; } } _builder.Append('"'); }
        }
    }
}
