namespace AIBT.Burst
{
    // This public seam is reserved for generated consumer assemblies. P2-004
    // publishes the frozen ABI only; native ownership and dispatch are supplied
    // by their dedicated runtime work items. Default values therefore fail closed.
    public static class BurstGeneratedRuntimeBridge
    {
        public static BurstContextResult TryGetCatalogHandshake(in BurstExecutionBatch batch, out BurstCatalogHandshake handshake) => BurstDispatchBridgeCoreV2.TryGetCatalogHandshake(in batch, out handshake);
        public static BurstContextResult TryRejectBatch(ref BurstExecutionBatch batch, in BurstCatalogValidationResult validationResult) => BurstDispatchBridgeCoreV2.TryRejectBatch(ref batch, in validationResult);
        public static BurstContextResult TryGetExecutionRequest(in BurstExecutionBatch batch, out uint instanceOrdinal, out uint runtimeNodeIndex, out uint catalogCaseIndex, out BurstCallbackPhase phase, out bool hasWork)
        {
            return BurstDispatchBridgeCoreV2.TryGetExecutionRequest(in batch, out instanceOrdinal, out runtimeNodeIndex, out catalogCaseIndex, out phase, out hasWork);
        }

        public static BurstContextResult TryGetExecutionResult(in BurstExecutionBatch batch, out BurstExecutionResult result) => BurstDispatchBridgeCoreV2.TryGetExecutionResult(in batch, out result);
        public static BurstContextResult TryPrepareSchedule(ref BurstExecutionBatch batch, out BurstExecutionBatch scheduledView) => BurstDispatchBridgeCoreV2.TryPrepareSchedule(ref batch, out scheduledView);
        public static BurstContextResult TryAcquireDispatchFrame(ref BurstExecutionBatch batch, uint instanceOrdinal, uint runtimeNodeIndex, uint catalogCaseIndex, BurstCallbackPhase phase, out BurstDispatchFrame frame) => BurstDispatchBridgeCoreV2.TryAcquireDispatchFrame(ref batch, instanceOrdinal, runtimeNodeIndex, catalogCaseIndex, phase, out frame);
        public static BurstContextResult TryCreateConfigurationReader(in BurstDispatchFrame frame, out BurstConfigurationReader reader) => BurstDispatchBridgeCoreV2.TryCreateConfigurationReader(in frame, out reader);
        public static BurstContextResult TryCreateMemoryAccessor(in BurstDispatchFrame frame, out BurstMemoryAccessor accessor) => BurstDispatchBridgeCoreV2.TryCreateMemoryAccessor(in frame, out accessor);

        public static BurstContextResult TryReadBoolean(ref BurstConfigurationReader reader, uint fieldOrdinal, uint elementIndex, out bool value) => BurstDispatchBridgeCoreV2.TryReadConfiguration(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Boolean, out value);
        public static BurstContextResult TryReadUInt32(ref BurstConfigurationReader reader, uint fieldOrdinal, uint elementIndex, out uint value) => BurstDispatchBridgeCoreV2.TryReadConfiguration(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt32, out value);
        public static BurstContextResult TryReadUInt64(ref BurstConfigurationReader reader, uint fieldOrdinal, uint elementIndex, out ulong value) => BurstDispatchBridgeCoreV2.TryReadConfiguration(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt64, out value);

        public static BurstContextResult TryReadBlackboardReadHandle<T>(ref BurstConfigurationReader reader, uint fieldOrdinal, ulong valueTypeNumericId, uint valueTypeVersion, out BlackboardReadHandle<T> value) where T : unmanaged => BurstBindingBridgeCoreV2.TryReadBlackboardReadHandle(ref reader, fieldOrdinal, valueTypeNumericId, valueTypeVersion, out value);
        public static BurstContextResult TryReadBlackboardWriteHandle<T>(ref BurstConfigurationReader reader, uint fieldOrdinal, ulong valueTypeNumericId, uint valueTypeVersion, out BlackboardWriteHandle<T> value) where T : unmanaged => BurstBindingBridgeCoreV2.TryReadBlackboardWriteHandle(ref reader, fieldOrdinal, valueTypeNumericId, valueTypeVersion, out value);
        public static BurstContextResult TryReadBlackboardReadWriteHandle<T>(ref BurstConfigurationReader reader, uint fieldOrdinal, ulong valueTypeNumericId, uint valueTypeVersion, out BlackboardReadWriteHandle<T> value) where T : unmanaged => BurstBindingBridgeCoreV2.TryReadBlackboardReadWriteHandle(ref reader, fieldOrdinal, valueTypeNumericId, valueTypeVersion, out value);
        public static BurstContextResult TryReadSnapshotHandle<T>(ref BurstConfigurationReader reader, uint fieldOrdinal, ulong valueTypeNumericId, uint valueTypeVersion, out SnapshotReadHandle<T> value) where T : unmanaged => BurstBindingBridgeCoreV2.TryReadSnapshotHandle(ref reader, fieldOrdinal, valueTypeNumericId, valueTypeVersion, out value);
        public static BurstContextResult TryReadCommandHandle<T>(ref BurstConfigurationReader reader, uint fieldOrdinal, ulong payloadTypeNumericId, uint payloadTypeVersion, out CommandHandle<T> value) where T : unmanaged => BurstBindingBridgeCoreV2.TryReadCommandHandle(ref reader, fieldOrdinal, payloadTypeNumericId, payloadTypeVersion, out value);
        public static BurstContextResult TryReadAsyncOperationHandle<TStart, TCancel>(ref BurstConfigurationReader reader, uint fieldOrdinal, ulong startPayloadTypeNumericId, uint startPayloadTypeVersion, ulong cancelPayloadTypeNumericId, uint cancelPayloadTypeVersion, out AsyncOperationHandle<TStart, TCancel> value) where TStart : unmanaged where TCancel : unmanaged => BurstBindingBridgeCoreV2.TryReadAsyncOperationHandle(ref reader, fieldOrdinal, startPayloadTypeNumericId, startPayloadTypeVersion, cancelPayloadTypeNumericId, cancelPayloadTypeVersion, out value);
        public static BurstContextResult TryReadCompletionHandle<T>(ref BurstConfigurationReader reader, uint fieldOrdinal, ulong payloadTypeNumericId, uint payloadTypeVersion, out CompletionHandle<T> value) where T : unmanaged => BurstBindingBridgeCoreV2.TryReadCompletionHandle(ref reader, fieldOrdinal, payloadTypeNumericId, payloadTypeVersion, out value);

        public static BurstContextResult TryReadMemoryBoolean(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out bool value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Boolean, out value);
        public static BurstContextResult TryReadMemoryInt8(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out sbyte value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int8, out value);
        public static BurstContextResult TryReadMemoryUInt8(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out byte value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt8, out value);
        public static BurstContextResult TryReadMemoryInt16(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out short value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int16, out value);
        public static BurstContextResult TryReadMemoryUInt16(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out ushort value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt16, out value);
        public static BurstContextResult TryReadMemoryInt32(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out int value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int32, out value);
        public static BurstContextResult TryReadMemoryUInt32(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out uint value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt32, out value);
        public static BurstContextResult TryReadMemoryInt64(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out long value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int64, out value);
        public static BurstContextResult TryReadMemoryUInt64(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out ulong value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt64, out value);
        public static BurstContextResult TryReadMemoryFloat32(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out float value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Float32, out value);
        public static BurstContextResult TryReadMemoryFloat64(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, out double value) => BurstDispatchBridgeCoreV2.TryReadMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Float64, out value);

        public static BurstContextResult TryWriteMemoryBoolean(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, bool value) => BurstDispatchBridgeCoreV2.TryWriteMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Boolean, value);
        public static BurstContextResult TryWriteMemoryInt8(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, sbyte value) => BurstDispatchBridgeCoreV2.TryWriteMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int8, value);
        public static BurstContextResult TryWriteMemoryUInt8(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, byte value) => BurstDispatchBridgeCoreV2.TryWriteMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt8, value);
        public static BurstContextResult TryWriteMemoryInt16(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, short value) => BurstDispatchBridgeCoreV2.TryWriteMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int16, value);
        public static BurstContextResult TryWriteMemoryUInt16(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, ushort value) => BurstDispatchBridgeCoreV2.TryWriteMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt16, value);
        public static BurstContextResult TryWriteMemoryInt32(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, int value) => BurstDispatchBridgeCoreV2.TryWriteMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int32, value);
        public static BurstContextResult TryWriteMemoryUInt32(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, uint value) => BurstDispatchBridgeCoreV2.TryWriteMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt32, value);
        public static BurstContextResult TryWriteMemoryInt64(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, long value) => BurstDispatchBridgeCoreV2.TryWriteMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int64, value);
        public static BurstContextResult TryWriteMemoryUInt64(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, ulong value) => BurstDispatchBridgeCoreV2.TryWriteMemory(ref accessor, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt64, value);
        public static BurstContextResult TryWriteMemoryFloat32(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, float value) => BurstDispatchBridgeCoreV2.TryWriteMemoryFloat32(ref accessor, fieldOrdinal, elementIndex, value);
        public static BurstContextResult TryWriteMemoryFloat64(ref BurstMemoryAccessor accessor, uint fieldOrdinal, uint elementIndex, double value) => BurstDispatchBridgeCoreV2.TryWriteMemoryFloat64(ref accessor, fieldOrdinal, elementIndex, value);
        public static BurstContextResult TryCommitMemory(ref BurstMemoryAccessor accessor) => BurstDispatchBridgeCoreV2.TryCommitMemory(ref accessor);

        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out bool value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Boolean, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out sbyte value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int8, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out byte value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt8, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out short value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int16, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out ushort value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt16, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out int value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int32, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out uint value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt32, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out long value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int64, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out ulong value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt64, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out float value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Float32, out value);
        public static BurstContextResult TryReadValue(ref BurstValueReader reader, uint fieldOrdinal, uint elementIndex, out double value) => BurstBindingBridgeCoreV2.TryReadValue(ref reader, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Float64, out value);
        public static BurstContextResult TryCompleteValueRead(ref BurstValueReader reader) => BurstBindingBridgeCoreV2.TryCompleteValueRead(ref reader);

        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, bool value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Boolean, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, sbyte value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int8, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, byte value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt8, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, short value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int16, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, ushort value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt16, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, int value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int32, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, uint value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt32, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, long value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Int64, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, ulong value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.UInt64, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, float value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Float32, value);
        public static BurstContextResult TryWriteValue(ref BurstValueWriter writer, uint fieldOrdinal, uint elementIndex, double value) => BurstBindingBridgeCoreV2.TryWriteValue(ref writer, fieldOrdinal, elementIndex, AIBT.Execution.Burst.Dispatch.NativeBurstDispatchFieldEncodingV2.Float64, value);
        public static BurstContextResult TryCommitBlackboardWrite(ref BurstValueWriter writer) => BurstBindingBridgeCoreV2.TryCommitBlackboardWrite(ref writer);
        public static BurstContextResult TryCommitEffect(ref BurstValueWriter writer) => BurstBindingBridgeCoreV2.TryCommitEffect(ref writer);
        public static BurstContextResult TryCommitStart(ref BurstValueWriter startWriter, ref BurstValueWriter faultCancelWriter, out AIBT.OperationId operationId) => BurstBindingBridgeCoreV2.TryCommitStart(ref startWriter, ref faultCancelWriter, out operationId);
        public static BurstContextResult TryCommitCancel(ref BurstValueWriter writer) => BurstBindingBridgeCoreV2.TryCommitCancel(ref writer);
        public static BurstContextResult TryCommitConsume(ref BurstValueReader reader) => BurstBindingBridgeCoreV2.TryCommitConsume(ref reader);

        public static BurstContextResult TryCreateEnterContext(in BurstDispatchFrame frame, out BurstEnterContext context) => BurstDispatchBridgeCoreV2.TryCreateEnterContext(in frame, out context);
        public static BurstContextResult TryCreateTickContext(in BurstDispatchFrame frame, out BurstTickContext context) => BurstDispatchBridgeCoreV2.TryCreateTickContext(in frame, out context);
        public static BurstContextResult TryCreateAbortContext(in BurstDispatchFrame frame, out BurstAbortContext context) => BurstDispatchBridgeCoreV2.TryCreateAbortContext(in frame, out context);
        public static BurstContextResult TryCreateExitContext(in BurstDispatchFrame frame, out BurstExitContext context) => BurstDispatchBridgeCoreV2.TryCreateExitContext(in frame, out context);
        public static BurstContextResult TryCreateObserverContext(in BurstDispatchFrame frame, out BurstObserverContext context) => BurstDispatchBridgeCoreV2.TryCreateObserverContext(in frame, out context);
        public static BurstContextResult TryGetAbortReason(in BurstDispatchFrame frame, out BurstNodeAbortReason reason) => BurstDispatchBridgeCoreV2.TryGetAbortReason(in frame, out reason);
        public static BurstContextResult TryGetExitReason(in BurstDispatchFrame frame, out BurstNodeExitReason reason) => BurstDispatchBridgeCoreV2.TryGetExitReason(in frame, out reason);
        public static BurstContextResult TryCompleteEnter(ref BurstExecutionBatch batch, in BurstDispatchFrame frame, ref BurstEnterContext context) => BurstDispatchBridgeCoreV2.TryCompleteEnter(ref batch, in frame, ref context);
        public static BurstContextResult TryCompleteTick(ref BurstExecutionBatch batch, in BurstDispatchFrame frame, ref BurstTickContext context, AIBT.NodeStatus status) => BurstDispatchBridgeCoreV2.TryCompleteTick(ref batch, in frame, ref context, status);
        public static BurstContextResult TryCompleteAbort(ref BurstExecutionBatch batch, in BurstDispatchFrame frame) => BurstDispatchBridgeCoreV2.TryCompleteSimple(ref batch, in frame, BurstCallbackPhase.Abort);
        public static BurstContextResult TryCompleteExit(ref BurstExecutionBatch batch, in BurstDispatchFrame frame) => BurstDispatchBridgeCoreV2.TryCompleteSimple(ref batch, in frame, BurstCallbackPhase.Exit);
        public static BurstContextResult TryCompleteObserver(ref BurstExecutionBatch batch, in BurstDispatchFrame frame, ConditionResult result) => BurstDispatchBridgeCoreV2.TryCompleteObserver(ref batch, in frame, result);
        public static BurstContextResult TryFailDispatch(ref BurstExecutionBatch batch, in BurstDispatchFrame frame, BurstContextResult failure) => BurstDispatchBridgeCoreV2.TryFailDispatch(ref batch, in frame, failure);
    }
}
