namespace AIBT.Burst
{
    internal static class RuntimeBuiltInCatalogAuthority
    {
        public const uint FormatVersion = 1u;

        public const string ManifestRegistryJson =
            "{\n"
            + "  \"format\": \"aibt-node-registry\",\n"
            + "  \"formatVersion\": 1,\n"
            + "  \"manifests\": [\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.cooldown\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Block child entry until the per-instance cooldown deadline has passed.\",\n"
            + "      \"category\": \"Cooldown\",\n"
            + "      \"kind\": \"decorator\",\n"
            + "      \"whenToUse\": \"Use to rate-limit child activation without a tree blackboard key.\",\n"
            + "      \"whenNotToUse\": \"Do not use when cooldown state must be shared across tree instances.\",\n"
            + "      \"parameters\": {\n"
            + "        \"blockedResult\": {\n"
            + "          \"type\": \"string-enum\",\n"
            + "          \"required\": true,\n"
            + "          \"allowedValues\": [\n"
            + "            \"failure\",\n"
            + "            \"success\"\n"
            + "          ],\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 8,\n"
            + "            \"size\": 1,\n"
            + "            \"alignment\": 1\n"
            + "          }\n"
            + "        },\n"
            + "        \"durationMicroseconds\": {\n"
            + "          \"type\": \"uint64\",\n"
            + "          \"required\": true,\n"
            + "          \"minimum\": 1,\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 0,\n"
            + "            \"size\": 8,\n"
            + "            \"alignment\": 8\n"
            + "          }\n"
            + "        },\n"
            + "        \"startPolicy\": {\n"
            + "          \"type\": \"string-enum\",\n"
            + "          \"required\": true,\n"
            + "          \"allowedValues\": [\n"
            + "            \"on-enter\",\n"
            + "            \"on-successful-exit\"\n"
            + "          ],\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 9,\n"
            + "            \"size\": 1,\n"
            + "            \"alignment\": 1\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 1,\n"
            + "        \"maximum\": 1,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 8,\n"
            + "        \"alignment\": 8,\n"
            + "        \"lifetime\": \"instance\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 16,\n"
            + "        \"alignment\": 8\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {\n"
            + "            \"blockedResult\": \"failure\",\n"
            + "            \"durationMicroseconds\": 1000000,\n"
            + "            \"startPolicy\": \"on-enter\"\n"
            + "          },\n"
            + "          \"expectedBehavior\": \"A blocked activation fails until one second after child entry.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.failer\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Convert either terminal child result to failure while preserving running.\",\n"
            + "      \"category\": \"Failer\",\n"
            + "      \"kind\": \"decorator\",\n"
            + "      \"whenToUse\": \"Use when child completion must force a fallback path.\",\n"
            + "      \"whenNotToUse\": \"Do not use to discard a success that callers need to observe.\",\n"
            + "      \"parameters\": {},\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 1,\n"
            + "        \"maximum\": 1,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {},\n"
            + "          \"expectedBehavior\": \"A successful child makes the failer fail.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.inverter\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Invert terminal success and failure while preserving running.\",\n"
            + "      \"category\": \"Inverter\",\n"
            + "      \"kind\": \"decorator\",\n"
            + "      \"whenToUse\": \"Use to negate a child's terminal meaning.\",\n"
            + "      \"whenNotToUse\": \"Do not use when either terminal result must be preserved.\",\n"
            + "      \"parameters\": {},\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 1,\n"
            + "        \"maximum\": 1,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {},\n"
            + "          \"expectedBehavior\": \"A successful child makes the inverter fail.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.memory-selector\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Run ordered children until one succeeds or runs, retaining the running child.\",\n"
            + "      \"category\": \"Memory selector\",\n"
            + "      \"kind\": \"composite\",\n"
            + "      \"whenToUse\": \"Use for fallback behavior whose earlier failed choices need not be reevaluated.\",\n"
            + "      \"whenNotToUse\": \"Do not use when a higher-priority choice must preempt a running lower-priority choice.\",\n"
            + "      \"parameters\": {},\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 0,\n"
            + "        \"maximum\": null,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 4,\n"
            + "        \"alignment\": 4,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {},\n"
            + "          \"expectedBehavior\": \"An empty memory selector fails.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.memory-sequence\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Run ordered children until one fails or runs, retaining the running child.\",\n"
            + "      \"category\": \"Memory sequence\",\n"
            + "      \"kind\": \"composite\",\n"
            + "      \"whenToUse\": \"Use for ordered multi-step behavior whose completed steps should not be reevaluated.\",\n"
            + "      \"whenNotToUse\": \"Do not use when earlier conditions must be checked on every update.\",\n"
            + "      \"parameters\": {},\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 0,\n"
            + "        \"maximum\": null,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 4,\n"
            + "        \"alignment\": 4,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {},\n"
            + "          \"expectedBehavior\": \"An empty memory sequence succeeds.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.parallel\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Visit each non-terminal child in order and complete according to an explicit policy.\",\n"
            + "      \"category\": \"Parallel\",\n"
            + "      \"kind\": \"composite\",\n"
            + "      \"whenToUse\": \"Use when several child behaviors must progress during the same activation.\",\n"
            + "      \"whenNotToUse\": \"Do not use to imply simultaneous execution or worker-thread concurrency.\",\n"
            + "      \"parameters\": {\n"
            + "        \"failureThreshold\": {\n"
            + "          \"type\": \"uint32\",\n"
            + "          \"required\": false,\n"
            + "          \"minimum\": 1,\n"
            + "          \"requiredWhen\": {\n"
            + "            \"parameter\": \"policy\",\n"
            + "            \"equals\": \"threshold\"\n"
            + "          },\n"
            + "          \"forbiddenUnless\": {\n"
            + "            \"parameter\": \"policy\",\n"
            + "            \"equals\": \"threshold\"\n"
            + "          },\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 8,\n"
            + "            \"size\": 4,\n"
            + "            \"alignment\": 4\n"
            + "          }\n"
            + "        },\n"
            + "        \"policy\": {\n"
            + "          \"type\": \"string-enum\",\n"
            + "          \"required\": true,\n"
            + "          \"allowedValues\": [\n"
            + "            \"require-all-success\",\n"
            + "            \"require-any-success\",\n"
            + "            \"threshold\"\n"
            + "          ],\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 0,\n"
            + "            \"size\": 1,\n"
            + "            \"alignment\": 1\n"
            + "          }\n"
            + "        },\n"
            + "        \"successThreshold\": {\n"
            + "          \"type\": \"uint32\",\n"
            + "          \"required\": false,\n"
            + "          \"minimum\": 1,\n"
            + "          \"requiredWhen\": {\n"
            + "            \"parameter\": \"policy\",\n"
            + "            \"equals\": \"threshold\"\n"
            + "          },\n"
            + "          \"forbiddenUnless\": {\n"
            + "            \"parameter\": \"policy\",\n"
            + "            \"equals\": \"threshold\"\n"
            + "          },\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 4,\n"
            + "            \"size\": 4,\n"
            + "            \"alignment\": 4\n"
            + "          }\n"
            + "        },\n"
            + "        \"tieBreak\": {\n"
            + "          \"type\": \"string-enum\",\n"
            + "          \"required\": false,\n"
            + "          \"allowedValues\": [\n"
            + "            \"failure-first\",\n"
            + "            \"success-first\"\n"
            + "          ],\n"
            + "          \"requiredWhen\": {\n"
            + "            \"parameter\": \"policy\",\n"
            + "            \"equals\": \"threshold\"\n"
            + "          },\n"
            + "          \"forbiddenUnless\": {\n"
            + "            \"parameter\": \"policy\",\n"
            + "            \"equals\": \"threshold\"\n"
            + "          },\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 12,\n"
            + "            \"size\": 1,\n"
            + "            \"alignment\": 1\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 1,\n"
            + "        \"maximum\": null,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 8,\n"
            + "        \"alignment\": 4,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 16,\n"
            + "        \"alignment\": 4\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"medium\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Require all\",\n"
            + "          \"parameters\": {\n"
            + "            \"policy\": \"require-all-success\"\n"
            + "          },\n"
            + "          \"expectedBehavior\": \"Succeeds after every child succeeds and fails after any child fails.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.reactive-selector\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Reevaluate ordered choices from the highest priority on every eligible update.\",\n"
            + "      \"category\": \"Reactive selector\",\n"
            + "      \"kind\": \"composite\",\n"
            + "      \"whenToUse\": \"Use for priority behavior in which earlier choices can replace a running later choice.\",\n"
            + "      \"whenNotToUse\": \"Do not use when the chosen branch must run without priority reevaluation.\",\n"
            + "      \"parameters\": {},\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 0,\n"
            + "        \"maximum\": null,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 4,\n"
            + "        \"alignment\": 4,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {},\n"
            + "          \"expectedBehavior\": \"An empty reactive selector fails.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.reactive-sequence\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Reevaluate ordered children from the first child on every eligible update.\",\n"
            + "      \"category\": \"Reactive sequence\",\n"
            + "      \"kind\": \"composite\",\n"
            + "      \"whenToUse\": \"Use when earlier conditions must continuously guard a later action.\",\n"
            + "      \"whenNotToUse\": \"Do not use when restarting the selected running branch is undesirable.\",\n"
            + "      \"parameters\": {},\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 0,\n"
            + "        \"maximum\": null,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 4,\n"
            + "        \"alignment\": 4,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {},\n"
            + "          \"expectedBehavior\": \"An empty reactive sequence succeeds.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.repeater\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Run a child for a positive finite number of complete iterations.\",\n"
            + "      \"category\": \"Repeater\",\n"
            + "      \"kind\": \"decorator\",\n"
            + "      \"whenToUse\": \"Use for bounded repetition with explicit failure behavior.\",\n"
            + "      \"whenNotToUse\": \"Do not use for an unbounded loop.\",\n"
            + "      \"parameters\": {\n"
            + "        \"count\": {\n"
            + "          \"type\": \"uint32\",\n"
            + "          \"required\": true,\n"
            + "          \"minimum\": 1,\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 0,\n"
            + "            \"size\": 4,\n"
            + "            \"alignment\": 4\n"
            + "          }\n"
            + "        },\n"
            + "        \"stopOnFailure\": {\n"
            + "          \"type\": \"boolean\",\n"
            + "          \"required\": true,\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 4,\n"
            + "            \"size\": 1,\n"
            + "            \"alignment\": 1\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 1,\n"
            + "        \"maximum\": 1,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 4,\n"
            + "        \"alignment\": 4,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 8,\n"
            + "        \"alignment\": 4\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {\n"
            + "            \"count\": 3,\n"
            + "            \"stopOnFailure\": true\n"
            + "          },\n"
            + "          \"expectedBehavior\": \"Three successful child iterations complete with success.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.succeeder\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Convert either terminal child result to success while preserving running.\",\n"
            + "      \"category\": \"Succeeder\",\n"
            + "      \"kind\": \"decorator\",\n"
            + "      \"whenToUse\": \"Use when child completion, rather than its terminal result, is what matters.\",\n"
            + "      \"whenNotToUse\": \"Do not use to hide a failure that callers need to handle.\",\n"
            + "      \"parameters\": {},\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 1,\n"
            + "        \"maximum\": 1,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 0,\n"
            + "        \"alignment\": 1\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {},\n"
            + "          \"expectedBehavior\": \"A failed child makes the succeeder succeed.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"typeId\": \"aibt.core.timeout\",\n"
            + "      \"version\": 1,\n"
            + "      \"summary\": \"Abort a running child at a positive injected-clock deadline.\",\n"
            + "      \"category\": \"Timeout\",\n"
            + "      \"kind\": \"decorator\",\n"
            + "      \"whenToUse\": \"Use to bound how long a child activation may remain running.\",\n"
            + "      \"whenNotToUse\": \"Do not use wall-clock time directly or a zero duration.\",\n"
            + "      \"parameters\": {\n"
            + "        \"durationMicroseconds\": {\n"
            + "          \"type\": \"uint64\",\n"
            + "          \"required\": true,\n"
            + "          \"minimum\": 1,\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 0,\n"
            + "            \"size\": 8,\n"
            + "            \"alignment\": 8\n"
            + "          }\n"
            + "        },\n"
            + "        \"terminalResult\": {\n"
            + "          \"type\": \"string-enum\",\n"
            + "          \"required\": true,\n"
            + "          \"allowedValues\": [\n"
            + "            \"failure\",\n"
            + "            \"success\"\n"
            + "          ],\n"
            + "          \"packing\": {\n"
            + "            \"offset\": 8,\n"
            + "            \"size\": 1,\n"
            + "            \"alignment\": 1\n"
            + "          }\n"
            + "        }\n"
            + "      },\n"
            + "      \"childPolicy\": {\n"
            + "        \"minimum\": 1,\n"
            + "        \"maximum\": 1,\n"
            + "        \"ordered\": true\n"
            + "      },\n"
            + "      \"reads\": [],\n"
            + "      \"writes\": [],\n"
            + "      \"sideEffects\": [],\n"
            + "      \"possibleStatuses\": [\n"
            + "        \"failure\",\n"
            + "        \"running\",\n"
            + "        \"success\"\n"
            + "      ],\n"
            + "      \"memory\": {\n"
            + "        \"size\": 8,\n"
            + "        \"alignment\": 8,\n"
            + "        \"lifetime\": \"activation\"\n"
            + "      },\n"
            + "      \"configuration\": {\n"
            + "        \"size\": 16,\n"
            + "        \"alignment\": 8\n"
            + "      },\n"
            + "      \"cancellation\": \"abort-only\",\n"
            + "      \"executionDomain\": \"burst\",\n"
            + "      \"deterministic\": true,\n"
            + "      \"costHint\": \"low\",\n"
            + "      \"examples\": [\n"
            + "        {\n"
            + "          \"title\": \"Base behavior\",\n"
            + "          \"parameters\": {\n"
            + "            \"durationMicroseconds\": 1000000,\n"
            + "            \"terminalResult\": \"failure\"\n"
            + "          },\n"
            + "          \"expectedBehavior\": \"After one second the running child is aborted and the decorator fails.\"\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  ]\n"
            + "}\n";

        public const string NodeRegistryHash = "6c8a5da9c88b677981a9bec5b714cbb20bc34f69d32440ea8f7efa830535bd66";
    }
}
